import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "./UI-components/Navbar";
import StoreProvider from "./StoreProvider";
import Footer from "./UI-components/Footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`inter.className`}>
        <Navbar />
        <StoreProvider>
          {children}
          
        </StoreProvider>
        <Footer />
      </body>
    </html>
  );
}
